### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by GLiTcH2** [waschmaschvanlu/shark-bait#2]
I am getting the following error in my server console: `SCRIPT ERROR: @shark-bait/shared/config.lua:7: vector3 requires 1 or 3 values`? I haven't changed anything in the script, I simply just downloaded the files as they are from here.

**Comment by waschmaschvanlu** [comment]
Oh sorry, this is fixed now! :) i accidently misswrote sometuing in the config! thanks for telling me!
